ahoyapi: v2
commands:
  vup:
    cmd: "vagrant up"
    usage: Start the vagrant box if one exists.

  vdown:
    cmd: "vagrant down"
    usage: Stop the vagrant box if one exists.

  ps:
    cmd: docker-compose ps "$@"
    usage: List the running docker-compose containers.

  start:
    cmd: docker-compose start "$@"
    usage: Start the docker-compose containers.

  stop:
    cmd: docker-compose stop "$@"
    usage: Stop the docker-compose containers.

  restart:
    cmd: docker-compose restart "$@"
    usage: Restart the docker-compose containers.

  drush:
    cmd: docker-compose run cli drush --root=docroot "$@"
    usage: Run drush commands in the cli service container.

  bash:
    cmd: docker-compose run "$1" bash
    usage: Start a shell in the container (like ssh without actual ssh).

  sqlc:
    cmd: "docker-compose run cli drush --root=docroot sqlc"
    usage: Connect to the default mysql database. Supports piping of data into the command.

  behat:
    cmd: docker-compose run cli bash -c "cd docroot/test && composer install --prefer-source --no-interaction && bin/behat -p docker $@"
    usage: Run the behat tests within the container.

  behat-init:
    cmd: 'docker-compose run cli bash -c "cd docroot/test && composer install --prefer-source --no-interaction"'
    usage: Use composer to install behat dependencies.

  #This command overrides the up command in the docker.ahoy.yml to test the "last in wins" feature of ahoy
  up:
    cmd: "docker-compose up -d"
    usage: Start the docker-compose containers.

  sync-start:
    cmd: "docker-sync start"
    usage: Docker Sync Start.

  sync-logs:
    cmd: "docker-sync logs"
    usage: Docker Sync show logs.

  sync-sync:
    cmd: "docker-sync sync"
    usage: Docker Sync Sync.

  sync-stop:
    cmd: "docker-sync stop"
    usage: Docker Sync Stop.

  sync-clean:
    cmd: "docker-sync clean"
    usage: Docker Sync Clean.

  restart-sync:
    cmd: "docker-sync stop && docker-sync start"
    usage: Restart Docker Sync.

  sql-dev-imp:
    cmd: "drush sql-cli < ../mariadb-init/dev_db_12.sql"
    usage: Import dev DB.

  sql-live-imp-d7:
    cmd: "mysql -u drupal -pdrupal -h mariadb2 drupal7 < ../mariadb-init/live_d7_db.sql"
    usage: Import Live D7 DB.

  docker-clean-1:
    cmd: "docker stop $(docker ps -aq)"
    usage: Docker Stop running containers.

  docker-clean-2:
    cmd: "docker container prune"
    usage: Docker Remove all stop containers.

  docker-clean-3:
    cmd: "docker volume rm $(docker volume ls -qf dangling=true)"
    usage: Docker Clear orphaned volumes.

  docker-clean-4:
    cmd: "docker image prune"
    usage: Docker Image prune.

  coding-standards:
    cmd: "./vendor/bin/phpcs --standard=phpcs.ruleset.xml --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md"
    usage: Docker Image prune.

  ssh-php:
    cmd: "docker exec -it  recombee_drupal8_project_php /bin/bash && cd docroot"
    usage: SSH Login in PHP container.

